apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: haxseeker/todo-app-api:latest # Replace with your actual image name
          ports:
            - containerPort: 3001 # Or the port your API listens on
          env:
            - name: DATABASE_URL
              value: postgres://postgres:password@postgres-service:5432/todos # Replace with your actual database credentials
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 3001 # Or the port your API listens on
      targetPort: 3001 # Or the port your API listens on
  type: ClusterIP # Use NodePort for external access during development